### ISSUE TITLE
Npml NPM package has "src" production dependency 

### ISSUE THREAD

**Issue by andrey-skl** [tenphi/numl#55]
Looks like [Simple Redis Cache](https://www.npmjs.com/package/src) isn't a runtime dependency of Numl. If so, it would be better to move under devDependencies

See https://github.com/tenphi/numl/blob/master/package.json#L17

**Comment by tenphi** [comment]
Thanks! I don't know how it got there. I will remove it soon.

**Comment by tenphi** [comment]
Remove in `v0.11.27`.
