### ISSUE TITLE
the name variable is undefined. 

### ISSUE THREAD

**Issue by jt3k** [tenphi/numl#70]
Hm... my linter doesn't display an error in this place.

https://github.com/tenphi/numl/blob/9f5e0805fa82682242b693c20d1fb36ba8716355/src/index.js#L81

**Comment by tenphi** [comment]
Thanks for noticing! This part is a dead code. I forgot to remove it or at least comment it.

This logic will be returned in v0.13 to support lazy loading for elements.

**Comment by tenphi** [comment]
Fixed in #e22bb912d208ce69ad04bbfbba243575a726e67d
