### ISSUE TITLE
Standalone minified version?

### ISSUE THREAD

**Issue by caracal7** [tenphi/numl#98]
As ES module

**Comment by tenphi** [comment]
Hi! What are you trying to achieve exactly?
Install `numl` as **npm package** and you will get a standalone minified ES version. Then import it into your app.

```
import 'numl';
```

**Comment by caracal7** [comment]
In one of my projects Im using not regular bundler that does not support every npm module.
But usually I don't have problems with standalone modules.

**Comment by tenphi** [comment]
Clone the repo.

```
$ npm i
$ npm run build
```

Then you will have a standalone minified ES version in the `dist` dir. There are many files in that dir. You need all of them.
